//@ run-fail

#[test]
fn intended_to_fail() {
    panic!()
}
